import os
from dotenv import load_dotenv

load_dotenv()

AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
LLM_MODEL = os.getenv("AZURE_OPENAI_DEPLOYMENT")

SIMILARITY_THRESHOLD = 0.7
CONFIDENCE_THRESHOLD = 0.65
AMBIGUITY_MARGIN = 0.08